# Generated by Django 4.0.4 on 2022-05-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='descrip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='m2_constru',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='m2_terreno',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='n_baño',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='n_hab',
            field=models.IntegerField(null=True),
        ),
    ]
