# Generated by Django 4.0.4 on 2022-05-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_descrip_alter_propiedad_m2_constru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='arriendo',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descrip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='m2_constru',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='m2_terreno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='n_baño',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='n_hab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
